### ISSUE TITLE
FreeRTOS and TCP/IP on PIC

### ISSUE THREAD

**Issue by robinrodricks** [grodansparadis/vscp-firmware#10]
Hi Ake Hedman,

On [this page](https://sourceforge.net/p/freertos/discussion/382005/thread/17f38532/) you said you managed to run FreeRTOS with the lwIP TCP/IP Stack. 

Can you tell me where in the `vscp_firmware` project I can find code related do this?

**Comment by grodansparadis** [comment]
Hi,

thats was old stuff!..  Must be the Sweetbox project.   It may be some 
code left here https://github.com/grodansparadis/sweetbox

Cheers
/Ake

On 16/04/16 11:23, Harsh Gupta wrote:
>
> Hi Ake Hedman,
>
> On this page 
> <https://sourceforge.net/p/freertos/discussion/382005/thread/17f38532/> you 
> said you managed to run FreeRTOS with the lwIP TCP/IP Stack.
>
> Can you tell me where in the |vscp_firmware| project I can find code 
> related do this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_firmware/issues/10>
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN, +46 8 40011835
http://www.grodansparadis.com http://www.vscp.org http://www.akehedman.se

**Comment by hgupta9** [comment]
Thank you Ake, any idea if HTTP and HTTPS requests are possible with your current port of lwIP?

**Comment by grodansparadis** [comment]
Hi,

if I did this today I would definitely gone for mongoose 
<https://docs.cesanta.com/mongoose/latest/>

Cheers
/Ake

On 17/04/16 10:25, Harsh Gupta wrote:
>
> Thank you Ake, any idea if HTTP and HTTPS requests are possible with 
> your current port of lwIP?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_firmware/issues/10#issuecomment-210974306>
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN, +46 8 40011835
http://www.grodansparadis.com http://www.vscp.org http://www.akehedman.se

**Comment by hgupta9** [comment]
Hi Ake,

Thank you very much for your recommendation! This looks so much better 
and simpler.

Kudos,
Harsh
